#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suiveStagaireProject.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SuiveStagiaire")]
	public partial class myLinqToSqlDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    partial void InsertEnseignant(Enseignant instance);
    partial void UpdateEnseignant(Enseignant instance);
    partial void DeleteEnseignant(Enseignant instance);
    partial void InsertDetailsStagiaire(DetailsStagiaire instance);
    partial void UpdateDetailsStagiaire(DetailsStagiaire instance);
    partial void DeleteDetailsStagiaire(DetailsStagiaire instance);
    partial void InsertBranchee(Branchee instance);
    partial void UpdateBranchee(Branchee instance);
    partial void DeleteBranchee(Branchee instance);
    partial void InsertCatalogeSection(CatalogeSection instance);
    partial void UpdateCatalogeSection(CatalogeSection instance);
    partial void DeleteCatalogeSection(CatalogeSection instance);
    partial void InsertModule(Module instance);
    partial void UpdateModule(Module instance);
    partial void DeleteModule(Module instance);
    partial void InsertEmployeur(Employeur instance);
    partial void UpdateEmployeur(Employeur instance);
    partial void DeleteEmployeur(Employeur instance);
    partial void InsertSection(Section instance);
    partial void UpdateSection(Section instance);
    partial void DeleteSection(Section instance);
    partial void InsertPersonnelInfo(PersonnelInfo instance);
    partial void UpdatePersonnelInfo(PersonnelInfo instance);
    partial void DeletePersonnelInfo(PersonnelInfo instance);
    partial void InsertStagiaire(Stagiaire instance);
    partial void UpdateStagiaire(Stagiaire instance);
    partial void DeleteStagiaire(Stagiaire instance);
    partial void InsertSeance(Seance instance);
    partial void UpdateSeance(Seance instance);
    partial void DeleteSeance(Seance instance);
    partial void InsertExam(Exam instance);
    partial void UpdateExam(Exam instance);
    partial void DeleteExam(Exam instance);
    partial void InsertNote(Note instance);
    partial void UpdateNote(Note instance);
    partial void DeleteNote(Note instance);
    partial void InsertSemestre(Semestre instance);
    partial void UpdateSemestre(Semestre instance);
    partial void DeleteSemestre(Semestre instance);
    #endregion
		
		public myLinqToSqlDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SuiveStagiaireConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public myLinqToSqlDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public myLinqToSqlDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public myLinqToSqlDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public myLinqToSqlDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
		
		public System.Data.Linq.Table<Enseignant> Enseignants
		{
			get
			{
				return this.GetTable<Enseignant>();
			}
		}
		
		public System.Data.Linq.Table<DetailsStagiaire> DetailsStagiaires
		{
			get
			{
				return this.GetTable<DetailsStagiaire>();
			}
		}
		
		public System.Data.Linq.Table<Branchee> Branchees
		{
			get
			{
				return this.GetTable<Branchee>();
			}
		}
		
		public System.Data.Linq.Table<CatalogeSection> CatalogeSections
		{
			get
			{
				return this.GetTable<CatalogeSection>();
			}
		}
		
		public System.Data.Linq.Table<Module> Modules
		{
			get
			{
				return this.GetTable<Module>();
			}
		}
		
		public System.Data.Linq.Table<Employeur> Employeurs
		{
			get
			{
				return this.GetTable<Employeur>();
			}
		}
		
		public System.Data.Linq.Table<Section> Sections
		{
			get
			{
				return this.GetTable<Section>();
			}
		}
		
		public System.Data.Linq.Table<PersonnelInfo> PersonnelInfos
		{
			get
			{
				return this.GetTable<PersonnelInfo>();
			}
		}
		
		public System.Data.Linq.Table<Stagiaire> Stagiaires
		{
			get
			{
				return this.GetTable<Stagiaire>();
			}
		}
		
		public System.Data.Linq.Table<Seance> Seances
		{
			get
			{
				return this.GetTable<Seance>();
			}
		}
		
		public System.Data.Linq.Table<Exam> Exams
		{
			get
			{
				return this.GetTable<Exam>();
			}
		}
		
		public System.Data.Linq.Table<Note> Notes
		{
			get
			{
				return this.GetTable<Note>();
			}
		}
		
		public System.Data.Linq.Table<Semestre> Semestres
		{
			get
			{
				return this.GetTable<Semestre>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Users")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _username;
		
		private string _password;
		
		private System.Nullable<int> _groupID;
		
		private System.Nullable<int> _trustID;
		
		private System.Nullable<System.DateTime> _date;
		
		private EntitySet<Enseignant> _Enseignants;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OngroupIDChanging(System.Nullable<int> value);
    partial void OngroupIDChanged();
    partial void OntrustIDChanging(System.Nullable<int> value);
    partial void OntrustIDChanged();
    partial void OndateChanging(System.Nullable<System.DateTime> value);
    partial void OndateChanged();
    #endregion
		
		public User()
		{
			this._Enseignants = new EntitySet<Enseignant>(new Action<Enseignant>(this.attach_Enseignants), new Action<Enseignant>(this.detach_Enseignants));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_groupID", DbType="Int")]
		public System.Nullable<int> groupID
		{
			get
			{
				return this._groupID;
			}
			set
			{
				if ((this._groupID != value))
				{
					this.OngroupIDChanging(value);
					this.SendPropertyChanging();
					this._groupID = value;
					this.SendPropertyChanged("groupID");
					this.OngroupIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trustID", DbType="Int")]
		public System.Nullable<int> trustID
		{
			get
			{
				return this._trustID;
			}
			set
			{
				if ((this._trustID != value))
				{
					this.OntrustIDChanging(value);
					this.SendPropertyChanging();
					this._trustID = value;
					this.SendPropertyChanged("trustID");
					this.OntrustIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this.OndateChanging(value);
					this.SendPropertyChanging();
					this._date = value;
					this.SendPropertyChanged("date");
					this.OndateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_Enseignant", Storage="_Enseignants", ThisKey="id", OtherKey="userId")]
		public EntitySet<Enseignant> Enseignants
		{
			get
			{
				return this._Enseignants;
			}
			set
			{
				this._Enseignants.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Enseignants(Enseignant entity)
		{
			this.SendPropertyChanging();
			entity.User = this;
		}
		
		private void detach_Enseignants(Enseignant entity)
		{
			this.SendPropertyChanging();
			entity.User = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Enseignant")]
	public partial class Enseignant : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idEnseiginant;
		
		private System.Nullable<System.DateTime> _dateDebut;
		
		private string _specialite;
		
		private System.Nullable<int> _userId;
		
		private System.Nullable<int> _personnelInfosId;
		
		private EntitySet<Seance> _Seances;
		
		private EntityRef<User> _User;
		
		private EntityRef<PersonnelInfo> _PersonnelInfo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidEnseiginantChanging(int value);
    partial void OnidEnseiginantChanged();
    partial void OndateDebutChanging(System.Nullable<System.DateTime> value);
    partial void OndateDebutChanged();
    partial void OnspecialiteChanging(string value);
    partial void OnspecialiteChanged();
    partial void OnuserIdChanging(System.Nullable<int> value);
    partial void OnuserIdChanged();
    partial void OnpersonnelInfosIdChanging(System.Nullable<int> value);
    partial void OnpersonnelInfosIdChanged();
    #endregion
		
		public Enseignant()
		{
			this._Seances = new EntitySet<Seance>(new Action<Seance>(this.attach_Seances), new Action<Seance>(this.detach_Seances));
			this._User = default(EntityRef<User>);
			this._PersonnelInfo = default(EntityRef<PersonnelInfo>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEnseiginant", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idEnseiginant
		{
			get
			{
				return this._idEnseiginant;
			}
			set
			{
				if ((this._idEnseiginant != value))
				{
					this.OnidEnseiginantChanging(value);
					this.SendPropertyChanging();
					this._idEnseiginant = value;
					this.SendPropertyChanged("idEnseiginant");
					this.OnidEnseiginantChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateDebut", DbType="Date")]
		public System.Nullable<System.DateTime> dateDebut
		{
			get
			{
				return this._dateDebut;
			}
			set
			{
				if ((this._dateDebut != value))
				{
					this.OndateDebutChanging(value);
					this.SendPropertyChanging();
					this._dateDebut = value;
					this.SendPropertyChanged("dateDebut");
					this.OndateDebutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_specialite", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string specialite
		{
			get
			{
				return this._specialite;
			}
			set
			{
				if ((this._specialite != value))
				{
					this.OnspecialiteChanging(value);
					this.SendPropertyChanging();
					this._specialite = value;
					this.SendPropertyChanged("specialite");
					this.OnspecialiteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userId", DbType="Int")]
		public System.Nullable<int> userId
		{
			get
			{
				return this._userId;
			}
			set
			{
				if ((this._userId != value))
				{
					if (this._User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnuserIdChanging(value);
					this.SendPropertyChanging();
					this._userId = value;
					this.SendPropertyChanged("userId");
					this.OnuserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_personnelInfosId", DbType="Int")]
		public System.Nullable<int> personnelInfosId
		{
			get
			{
				return this._personnelInfosId;
			}
			set
			{
				if ((this._personnelInfosId != value))
				{
					if (this._PersonnelInfo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnpersonnelInfosIdChanging(value);
					this.SendPropertyChanging();
					this._personnelInfosId = value;
					this.SendPropertyChanged("personnelInfosId");
					this.OnpersonnelInfosIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Enseignant_Seance", Storage="_Seances", ThisKey="idEnseiginant", OtherKey="idEns")]
		public EntitySet<Seance> Seances
		{
			get
			{
				return this._Seances;
			}
			set
			{
				this._Seances.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_Enseignant", Storage="_User", ThisKey="userId", OtherKey="id", IsForeignKey=true)]
		public User User
		{
			get
			{
				return this._User.Entity;
			}
			set
			{
				User previousValue = this._User.Entity;
				if (((previousValue != value) 
							|| (this._User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._User.Entity = null;
						previousValue.Enseignants.Remove(this);
					}
					this._User.Entity = value;
					if ((value != null))
					{
						value.Enseignants.Add(this);
						this._userId = value.id;
					}
					else
					{
						this._userId = default(Nullable<int>);
					}
					this.SendPropertyChanged("User");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PersonnelInfo_Enseignant", Storage="_PersonnelInfo", ThisKey="personnelInfosId", OtherKey="idPersonne", IsForeignKey=true)]
		public PersonnelInfo PersonnelInfo
		{
			get
			{
				return this._PersonnelInfo.Entity;
			}
			set
			{
				PersonnelInfo previousValue = this._PersonnelInfo.Entity;
				if (((previousValue != value) 
							|| (this._PersonnelInfo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PersonnelInfo.Entity = null;
						previousValue.Enseignants.Remove(this);
					}
					this._PersonnelInfo.Entity = value;
					if ((value != null))
					{
						value.Enseignants.Add(this);
						this._personnelInfosId = value.idPersonne;
					}
					else
					{
						this._personnelInfosId = default(Nullable<int>);
					}
					this.SendPropertyChanged("PersonnelInfo");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Seances(Seance entity)
		{
			this.SendPropertyChanging();
			entity.Enseignant = this;
		}
		
		private void detach_Seances(Seance entity)
		{
			this.SendPropertyChanging();
			entity.Enseignant = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DetailsStagiaire")]
	public partial class DetailsStagiaire : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _sang;
		
		private System.Nullable<int> _sitMedical;
		
		private string _prenomPere;
		
		private string _nomMere;
		
		private string _prenomMere;
		
		private string _telTuteur;
		
		private string _nat;
		
		private string _derEtabFre;
		
		private string _nivScolaire;
		
		private string _sitFam;
		
		private string _profPere;
		
		private string _profMere;
		
		private string _sitFamParents;
		
		private EntitySet<Stagiaire> _Stagiaires;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnsangChanging(string value);
    partial void OnsangChanged();
    partial void OnsitMedicalChanging(System.Nullable<int> value);
    partial void OnsitMedicalChanged();
    partial void OnprenomPereChanging(string value);
    partial void OnprenomPereChanged();
    partial void OnnomMereChanging(string value);
    partial void OnnomMereChanged();
    partial void OnprenomMereChanging(string value);
    partial void OnprenomMereChanged();
    partial void OntelTuteurChanging(string value);
    partial void OntelTuteurChanged();
    partial void OnnatChanging(string value);
    partial void OnnatChanged();
    partial void OnderEtabFreChanging(string value);
    partial void OnderEtabFreChanged();
    partial void OnnivScolaireChanging(string value);
    partial void OnnivScolaireChanged();
    partial void OnsitFamChanging(string value);
    partial void OnsitFamChanged();
    partial void OnprofPereChanging(string value);
    partial void OnprofPereChanged();
    partial void OnprofMereChanging(string value);
    partial void OnprofMereChanged();
    partial void OnsitFamParentsChanging(string value);
    partial void OnsitFamParentsChanged();
    #endregion
		
		public DetailsStagiaire()
		{
			this._Stagiaires = new EntitySet<Stagiaire>(new Action<Stagiaire>(this.attach_Stagiaires), new Action<Stagiaire>(this.detach_Stagiaires));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sang", DbType="VarChar(5)")]
		public string sang
		{
			get
			{
				return this._sang;
			}
			set
			{
				if ((this._sang != value))
				{
					this.OnsangChanging(value);
					this.SendPropertyChanging();
					this._sang = value;
					this.SendPropertyChanged("sang");
					this.OnsangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sitMedical", DbType="Int")]
		public System.Nullable<int> sitMedical
		{
			get
			{
				return this._sitMedical;
			}
			set
			{
				if ((this._sitMedical != value))
				{
					this.OnsitMedicalChanging(value);
					this.SendPropertyChanging();
					this._sitMedical = value;
					this.SendPropertyChanged("sitMedical");
					this.OnsitMedicalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prenomPere", DbType="VarChar(30)")]
		public string prenomPere
		{
			get
			{
				return this._prenomPere;
			}
			set
			{
				if ((this._prenomPere != value))
				{
					this.OnprenomPereChanging(value);
					this.SendPropertyChanging();
					this._prenomPere = value;
					this.SendPropertyChanged("prenomPere");
					this.OnprenomPereChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nomMere", DbType="VarChar(30)")]
		public string nomMere
		{
			get
			{
				return this._nomMere;
			}
			set
			{
				if ((this._nomMere != value))
				{
					this.OnnomMereChanging(value);
					this.SendPropertyChanging();
					this._nomMere = value;
					this.SendPropertyChanged("nomMere");
					this.OnnomMereChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prenomMere", DbType="VarChar(50)")]
		public string prenomMere
		{
			get
			{
				return this._prenomMere;
			}
			set
			{
				if ((this._prenomMere != value))
				{
					this.OnprenomMereChanging(value);
					this.SendPropertyChanging();
					this._prenomMere = value;
					this.SendPropertyChanged("prenomMere");
					this.OnprenomMereChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telTuteur", DbType="VarChar(15)")]
		public string telTuteur
		{
			get
			{
				return this._telTuteur;
			}
			set
			{
				if ((this._telTuteur != value))
				{
					this.OntelTuteurChanging(value);
					this.SendPropertyChanging();
					this._telTuteur = value;
					this.SendPropertyChanged("telTuteur");
					this.OntelTuteurChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nat", DbType="VarChar(30)")]
		public string nat
		{
			get
			{
				return this._nat;
			}
			set
			{
				if ((this._nat != value))
				{
					this.OnnatChanging(value);
					this.SendPropertyChanging();
					this._nat = value;
					this.SendPropertyChanged("nat");
					this.OnnatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_derEtabFre", DbType="VarChar(100)")]
		public string derEtabFre
		{
			get
			{
				return this._derEtabFre;
			}
			set
			{
				if ((this._derEtabFre != value))
				{
					this.OnderEtabFreChanging(value);
					this.SendPropertyChanging();
					this._derEtabFre = value;
					this.SendPropertyChanged("derEtabFre");
					this.OnderEtabFreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nivScolaire", DbType="VarChar(100)")]
		public string nivScolaire
		{
			get
			{
				return this._nivScolaire;
			}
			set
			{
				if ((this._nivScolaire != value))
				{
					this.OnnivScolaireChanging(value);
					this.SendPropertyChanging();
					this._nivScolaire = value;
					this.SendPropertyChanged("nivScolaire");
					this.OnnivScolaireChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sitFam", DbType="VarChar(20)")]
		public string sitFam
		{
			get
			{
				return this._sitFam;
			}
			set
			{
				if ((this._sitFam != value))
				{
					this.OnsitFamChanging(value);
					this.SendPropertyChanging();
					this._sitFam = value;
					this.SendPropertyChanged("sitFam");
					this.OnsitFamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_profPere", DbType="VarChar(50)")]
		public string profPere
		{
			get
			{
				return this._profPere;
			}
			set
			{
				if ((this._profPere != value))
				{
					this.OnprofPereChanging(value);
					this.SendPropertyChanging();
					this._profPere = value;
					this.SendPropertyChanged("profPere");
					this.OnprofPereChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_profMere", DbType="VarChar(50)")]
		public string profMere
		{
			get
			{
				return this._profMere;
			}
			set
			{
				if ((this._profMere != value))
				{
					this.OnprofMereChanging(value);
					this.SendPropertyChanging();
					this._profMere = value;
					this.SendPropertyChanged("profMere");
					this.OnprofMereChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sitFamParents", DbType="VarChar(20)")]
		public string sitFamParents
		{
			get
			{
				return this._sitFamParents;
			}
			set
			{
				if ((this._sitFamParents != value))
				{
					this.OnsitFamParentsChanging(value);
					this.SendPropertyChanging();
					this._sitFamParents = value;
					this.SendPropertyChanged("sitFamParents");
					this.OnsitFamParentsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DetailsStagiaire_Stagiaire", Storage="_Stagiaires", ThisKey="id", OtherKey="detailsInfoId")]
		public EntitySet<Stagiaire> Stagiaires
		{
			get
			{
				return this._Stagiaires;
			}
			set
			{
				this._Stagiaires.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Stagiaires(Stagiaire entity)
		{
			this.SendPropertyChanging();
			entity.DetailsStagiaire = this;
		}
		
		private void detach_Stagiaires(Stagiaire entity)
		{
			this.SendPropertyChanging();
			entity.DetailsStagiaire = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Branchees")]
	public partial class Branchee : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idBrache;
		
		private string _libileBrache;
		
		private string _LibileBracheAr;
		
		private EntitySet<CatalogeSection> _CatalogeSections;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidBracheChanging(int value);
    partial void OnidBracheChanged();
    partial void OnlibileBracheChanging(string value);
    partial void OnlibileBracheChanged();
    partial void OnLibileBracheArChanging(string value);
    partial void OnLibileBracheArChanged();
    #endregion
		
		public Branchee()
		{
			this._CatalogeSections = new EntitySet<CatalogeSection>(new Action<CatalogeSection>(this.attach_CatalogeSections), new Action<CatalogeSection>(this.detach_CatalogeSections));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idBrache", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idBrache
		{
			get
			{
				return this._idBrache;
			}
			set
			{
				if ((this._idBrache != value))
				{
					this.OnidBracheChanging(value);
					this.SendPropertyChanging();
					this._idBrache = value;
					this.SendPropertyChanged("idBrache");
					this.OnidBracheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_libileBrache", DbType="VarChar(50)")]
		public string libileBrache
		{
			get
			{
				return this._libileBrache;
			}
			set
			{
				if ((this._libileBrache != value))
				{
					this.OnlibileBracheChanging(value);
					this.SendPropertyChanging();
					this._libileBrache = value;
					this.SendPropertyChanged("libileBrache");
					this.OnlibileBracheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LibileBracheAr", DbType="VarChar(50)")]
		public string LibileBracheAr
		{
			get
			{
				return this._LibileBracheAr;
			}
			set
			{
				if ((this._LibileBracheAr != value))
				{
					this.OnLibileBracheArChanging(value);
					this.SendPropertyChanging();
					this._LibileBracheAr = value;
					this.SendPropertyChanged("LibileBracheAr");
					this.OnLibileBracheArChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Branchee_CatalogeSection", Storage="_CatalogeSections", ThisKey="idBrache", OtherKey="brancheId")]
		public EntitySet<CatalogeSection> CatalogeSections
		{
			get
			{
				return this._CatalogeSections;
			}
			set
			{
				this._CatalogeSections.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CatalogeSections(CatalogeSection entity)
		{
			this.SendPropertyChanging();
			entity.Branchee = this;
		}
		
		private void detach_CatalogeSections(CatalogeSection entity)
		{
			this.SendPropertyChanging();
			entity.Branchee = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CatalogeSection")]
	public partial class CatalogeSection : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idCataloge;
		
		private int _brancheId;
		
		private string _codeSpe;
		
		private string _intituleSpe;
		
		private string _intituleSpeAr;
		
		private string _fileresExigees;
		
		private int _niveauFormation;
		
		private EntitySet<Section> _Sections;
		
		private EntityRef<Branchee> _Branchee;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidCatalogeChanging(int value);
    partial void OnidCatalogeChanged();
    partial void OnbrancheIdChanging(int value);
    partial void OnbrancheIdChanged();
    partial void OncodeSpeChanging(string value);
    partial void OncodeSpeChanged();
    partial void OnintituleSpeChanging(string value);
    partial void OnintituleSpeChanged();
    partial void OnintituleSpeArChanging(string value);
    partial void OnintituleSpeArChanged();
    partial void OnfileresExigeesChanging(string value);
    partial void OnfileresExigeesChanged();
    partial void OnniveauFormationChanging(int value);
    partial void OnniveauFormationChanged();
    #endregion
		
		public CatalogeSection()
		{
			this._Sections = new EntitySet<Section>(new Action<Section>(this.attach_Sections), new Action<Section>(this.detach_Sections));
			this._Branchee = default(EntityRef<Branchee>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCataloge", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idCataloge
		{
			get
			{
				return this._idCataloge;
			}
			set
			{
				if ((this._idCataloge != value))
				{
					this.OnidCatalogeChanging(value);
					this.SendPropertyChanging();
					this._idCataloge = value;
					this.SendPropertyChanged("idCataloge");
					this.OnidCatalogeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_brancheId", DbType="Int NOT NULL")]
		public int brancheId
		{
			get
			{
				return this._brancheId;
			}
			set
			{
				if ((this._brancheId != value))
				{
					if (this._Branchee.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnbrancheIdChanging(value);
					this.SendPropertyChanging();
					this._brancheId = value;
					this.SendPropertyChanged("brancheId");
					this.OnbrancheIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codeSpe", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string codeSpe
		{
			get
			{
				return this._codeSpe;
			}
			set
			{
				if ((this._codeSpe != value))
				{
					this.OncodeSpeChanging(value);
					this.SendPropertyChanging();
					this._codeSpe = value;
					this.SendPropertyChanged("codeSpe");
					this.OncodeSpeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intituleSpe", DbType="VarChar(250)")]
		public string intituleSpe
		{
			get
			{
				return this._intituleSpe;
			}
			set
			{
				if ((this._intituleSpe != value))
				{
					this.OnintituleSpeChanging(value);
					this.SendPropertyChanging();
					this._intituleSpe = value;
					this.SendPropertyChanged("intituleSpe");
					this.OnintituleSpeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intituleSpeAr", DbType="VarChar(250)")]
		public string intituleSpeAr
		{
			get
			{
				return this._intituleSpeAr;
			}
			set
			{
				if ((this._intituleSpeAr != value))
				{
					this.OnintituleSpeArChanging(value);
					this.SendPropertyChanging();
					this._intituleSpeAr = value;
					this.SendPropertyChanged("intituleSpeAr");
					this.OnintituleSpeArChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fileresExigees", DbType="VarChar(50)")]
		public string fileresExigees
		{
			get
			{
				return this._fileresExigees;
			}
			set
			{
				if ((this._fileresExigees != value))
				{
					this.OnfileresExigeesChanging(value);
					this.SendPropertyChanging();
					this._fileresExigees = value;
					this.SendPropertyChanged("fileresExigees");
					this.OnfileresExigeesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_niveauFormation", DbType="Int NOT NULL")]
		public int niveauFormation
		{
			get
			{
				return this._niveauFormation;
			}
			set
			{
				if ((this._niveauFormation != value))
				{
					this.OnniveauFormationChanging(value);
					this.SendPropertyChanging();
					this._niveauFormation = value;
					this.SendPropertyChanged("niveauFormation");
					this.OnniveauFormationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CatalogeSection_Section", Storage="_Sections", ThisKey="idCataloge", OtherKey="idCat")]
		public EntitySet<Section> Sections
		{
			get
			{
				return this._Sections;
			}
			set
			{
				this._Sections.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Branchee_CatalogeSection", Storage="_Branchee", ThisKey="brancheId", OtherKey="idBrache", IsForeignKey=true)]
		public Branchee Branchee
		{
			get
			{
				return this._Branchee.Entity;
			}
			set
			{
				Branchee previousValue = this._Branchee.Entity;
				if (((previousValue != value) 
							|| (this._Branchee.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Branchee.Entity = null;
						previousValue.CatalogeSections.Remove(this);
					}
					this._Branchee.Entity = value;
					if ((value != null))
					{
						value.CatalogeSections.Add(this);
						this._brancheId = value.idBrache;
					}
					else
					{
						this._brancheId = default(int);
					}
					this.SendPropertyChanged("Branchee");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Sections(Section entity)
		{
			this.SendPropertyChanging();
			entity.CatalogeSection = this;
		}
		
		private void detach_Sections(Section entity)
		{
			this.SendPropertyChanging();
			entity.CatalogeSection = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Module")]
	public partial class Module : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idModule;
		
		private string _libelle;
		
		private EntitySet<Seance> _Seances;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidModuleChanging(int value);
    partial void OnidModuleChanged();
    partial void OnlibelleChanging(string value);
    partial void OnlibelleChanged();
    #endregion
		
		public Module()
		{
			this._Seances = new EntitySet<Seance>(new Action<Seance>(this.attach_Seances), new Action<Seance>(this.detach_Seances));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idModule", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idModule
		{
			get
			{
				return this._idModule;
			}
			set
			{
				if ((this._idModule != value))
				{
					this.OnidModuleChanging(value);
					this.SendPropertyChanging();
					this._idModule = value;
					this.SendPropertyChanged("idModule");
					this.OnidModuleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_libelle", DbType="VarChar(50)")]
		public string libelle
		{
			get
			{
				return this._libelle;
			}
			set
			{
				if ((this._libelle != value))
				{
					this.OnlibelleChanging(value);
					this.SendPropertyChanging();
					this._libelle = value;
					this.SendPropertyChanged("libelle");
					this.OnlibelleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Module_Seance", Storage="_Seances", ThisKey="idModule", OtherKey="idMod")]
		public EntitySet<Seance> Seances
		{
			get
			{
				return this._Seances;
			}
			set
			{
				this._Seances.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Seances(Seance entity)
		{
			this.SendPropertyChanging();
			entity.Module = this;
		}
		
		private void detach_Seances(Seance entity)
		{
			this.SendPropertyChanging();
			entity.Module = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Employeur")]
	public partial class Employeur : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idEpoloyeur;
		
		private string _Name;
		
		private string _Adresse;
		
		private string _status;
		
		private EntitySet<Stagiaire> _Stagiaires;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidEpoloyeurChanging(int value);
    partial void OnidEpoloyeurChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnAdresseChanging(string value);
    partial void OnAdresseChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    #endregion
		
		public Employeur()
		{
			this._Stagiaires = new EntitySet<Stagiaire>(new Action<Stagiaire>(this.attach_Stagiaires), new Action<Stagiaire>(this.detach_Stagiaires));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEpoloyeur", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idEpoloyeur
		{
			get
			{
				return this._idEpoloyeur;
			}
			set
			{
				if ((this._idEpoloyeur != value))
				{
					this.OnidEpoloyeurChanging(value);
					this.SendPropertyChanging();
					this._idEpoloyeur = value;
					this.SendPropertyChanged("idEpoloyeur");
					this.OnidEpoloyeurChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adresse", DbType="VarChar(150)")]
		public string Adresse
		{
			get
			{
				return this._Adresse;
			}
			set
			{
				if ((this._Adresse != value))
				{
					this.OnAdresseChanging(value);
					this.SendPropertyChanging();
					this._Adresse = value;
					this.SendPropertyChanged("Adresse");
					this.OnAdresseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="NChar(10)")]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Employeur_Stagiaire", Storage="_Stagiaires", ThisKey="idEpoloyeur", OtherKey="employeurId")]
		public EntitySet<Stagiaire> Stagiaires
		{
			get
			{
				return this._Stagiaires;
			}
			set
			{
				this._Stagiaires.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Stagiaires(Stagiaire entity)
		{
			this.SendPropertyChanging();
			entity.Employeur = this;
		}
		
		private void detach_Stagiaires(Stagiaire entity)
		{
			this.SendPropertyChanging();
			entity.Employeur = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Section")]
	public partial class Section : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _codeSection;
		
		private System.DateTime _dateOuv;
		
		private System.DateTime _dateFin;
		
		private string _tuteurSection;
		
		private char _modeGestionForm;
		
		private System.Nullable<int> _semestreId;
		
		private int _idCat;
		
		private EntitySet<Stagiaire> _Stagiaires;
		
		private EntitySet<Seance> _Seances;
		
		private EntityRef<CatalogeSection> _CatalogeSection;
		
		private EntityRef<Semestre> _Semestre;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodeSectionChanging(string value);
    partial void OncodeSectionChanged();
    partial void OndateOuvChanging(System.DateTime value);
    partial void OndateOuvChanged();
    partial void OndateFinChanging(System.DateTime value);
    partial void OndateFinChanged();
    partial void OntuteurSectionChanging(string value);
    partial void OntuteurSectionChanged();
    partial void OnmodeGestionFormChanging(char value);
    partial void OnmodeGestionFormChanged();
    partial void OnsemestreIdChanging(System.Nullable<int> value);
    partial void OnsemestreIdChanged();
    partial void OnidCatChanging(int value);
    partial void OnidCatChanged();
    #endregion
		
		public Section()
		{
			this._Stagiaires = new EntitySet<Stagiaire>(new Action<Stagiaire>(this.attach_Stagiaires), new Action<Stagiaire>(this.detach_Stagiaires));
			this._Seances = new EntitySet<Seance>(new Action<Seance>(this.attach_Seances), new Action<Seance>(this.detach_Seances));
			this._CatalogeSection = default(EntityRef<CatalogeSection>);
			this._Semestre = default(EntityRef<Semestre>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codeSection", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string codeSection
		{
			get
			{
				return this._codeSection;
			}
			set
			{
				if ((this._codeSection != value))
				{
					this.OncodeSectionChanging(value);
					this.SendPropertyChanging();
					this._codeSection = value;
					this.SendPropertyChanged("codeSection");
					this.OncodeSectionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateOuv", DbType="Date NOT NULL")]
		public System.DateTime dateOuv
		{
			get
			{
				return this._dateOuv;
			}
			set
			{
				if ((this._dateOuv != value))
				{
					this.OndateOuvChanging(value);
					this.SendPropertyChanging();
					this._dateOuv = value;
					this.SendPropertyChanged("dateOuv");
					this.OndateOuvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateFin", DbType="Date NOT NULL")]
		public System.DateTime dateFin
		{
			get
			{
				return this._dateFin;
			}
			set
			{
				if ((this._dateFin != value))
				{
					this.OndateFinChanging(value);
					this.SendPropertyChanging();
					this._dateFin = value;
					this.SendPropertyChanged("dateFin");
					this.OndateFinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tuteurSection", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string tuteurSection
		{
			get
			{
				return this._tuteurSection;
			}
			set
			{
				if ((this._tuteurSection != value))
				{
					this.OntuteurSectionChanging(value);
					this.SendPropertyChanging();
					this._tuteurSection = value;
					this.SendPropertyChanged("tuteurSection");
					this.OntuteurSectionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modeGestionForm", DbType="NChar(1) NOT NULL")]
		public char modeGestionForm
		{
			get
			{
				return this._modeGestionForm;
			}
			set
			{
				if ((this._modeGestionForm != value))
				{
					this.OnmodeGestionFormChanging(value);
					this.SendPropertyChanging();
					this._modeGestionForm = value;
					this.SendPropertyChanged("modeGestionForm");
					this.OnmodeGestionFormChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_semestreId", DbType="Int")]
		public System.Nullable<int> semestreId
		{
			get
			{
				return this._semestreId;
			}
			set
			{
				if ((this._semestreId != value))
				{
					if (this._Semestre.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnsemestreIdChanging(value);
					this.SendPropertyChanging();
					this._semestreId = value;
					this.SendPropertyChanged("semestreId");
					this.OnsemestreIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCat", DbType="Int NOT NULL")]
		public int idCat
		{
			get
			{
				return this._idCat;
			}
			set
			{
				if ((this._idCat != value))
				{
					if (this._CatalogeSection.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidCatChanging(value);
					this.SendPropertyChanging();
					this._idCat = value;
					this.SendPropertyChanged("idCat");
					this.OnidCatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Section_Stagiaire", Storage="_Stagiaires", ThisKey="codeSection", OtherKey="idSection")]
		public EntitySet<Stagiaire> Stagiaires
		{
			get
			{
				return this._Stagiaires;
			}
			set
			{
				this._Stagiaires.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Section_Seance", Storage="_Seances", ThisKey="codeSection", OtherKey="idSec")]
		public EntitySet<Seance> Seances
		{
			get
			{
				return this._Seances;
			}
			set
			{
				this._Seances.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CatalogeSection_Section", Storage="_CatalogeSection", ThisKey="idCat", OtherKey="idCataloge", IsForeignKey=true)]
		public CatalogeSection CatalogeSection
		{
			get
			{
				return this._CatalogeSection.Entity;
			}
			set
			{
				CatalogeSection previousValue = this._CatalogeSection.Entity;
				if (((previousValue != value) 
							|| (this._CatalogeSection.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CatalogeSection.Entity = null;
						previousValue.Sections.Remove(this);
					}
					this._CatalogeSection.Entity = value;
					if ((value != null))
					{
						value.Sections.Add(this);
						this._idCat = value.idCataloge;
					}
					else
					{
						this._idCat = default(int);
					}
					this.SendPropertyChanged("CatalogeSection");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Semestre_Section", Storage="_Semestre", ThisKey="semestreId", OtherKey="idSemestre", IsForeignKey=true)]
		public Semestre Semestre
		{
			get
			{
				return this._Semestre.Entity;
			}
			set
			{
				Semestre previousValue = this._Semestre.Entity;
				if (((previousValue != value) 
							|| (this._Semestre.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Semestre.Entity = null;
						previousValue.Sections.Remove(this);
					}
					this._Semestre.Entity = value;
					if ((value != null))
					{
						value.Sections.Add(this);
						this._semestreId = value.idSemestre;
					}
					else
					{
						this._semestreId = default(Nullable<int>);
					}
					this.SendPropertyChanged("Semestre");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Stagiaires(Stagiaire entity)
		{
			this.SendPropertyChanging();
			entity.Section = this;
		}
		
		private void detach_Stagiaires(Stagiaire entity)
		{
			this.SendPropertyChanging();
			entity.Section = null;
		}
		
		private void attach_Seances(Seance entity)
		{
			this.SendPropertyChanging();
			entity.Section = this;
		}
		
		private void detach_Seances(Seance entity)
		{
			this.SendPropertyChanging();
			entity.Section = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PersonnelInfo")]
	public partial class PersonnelInfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idPersonne;
		
		private string _nom;
		
		private string _nomAr;
		
		private string _prenom;
		
		private string _prenomAr;
		
		private System.Nullable<System.DateTime> _dateNai;
		
		private string _lieuNai;
		
		private string _lieuNaiAr;
		
		private string _sexe;
		
		private string _adresse;
		
		private string _adresseAr;
		
		private string _email;
		
		private string _telephone;
		
		private EntitySet<Enseignant> _Enseignants;
		
		private EntitySet<Stagiaire> _Stagiaires;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidPersonneChanging(int value);
    partial void OnidPersonneChanged();
    partial void OnnomChanging(string value);
    partial void OnnomChanged();
    partial void OnnomArChanging(string value);
    partial void OnnomArChanged();
    partial void OnprenomChanging(string value);
    partial void OnprenomChanged();
    partial void OnprenomArChanging(string value);
    partial void OnprenomArChanged();
    partial void OndateNaiChanging(System.Nullable<System.DateTime> value);
    partial void OndateNaiChanged();
    partial void OnlieuNaiChanging(string value);
    partial void OnlieuNaiChanged();
    partial void OnlieuNaiArChanging(string value);
    partial void OnlieuNaiArChanged();
    partial void OnsexeChanging(string value);
    partial void OnsexeChanged();
    partial void OnadresseChanging(string value);
    partial void OnadresseChanged();
    partial void OnadresseArChanging(string value);
    partial void OnadresseArChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OntelephoneChanging(string value);
    partial void OntelephoneChanged();
    #endregion
		
		public PersonnelInfo()
		{
			this._Enseignants = new EntitySet<Enseignant>(new Action<Enseignant>(this.attach_Enseignants), new Action<Enseignant>(this.detach_Enseignants));
			this._Stagiaires = new EntitySet<Stagiaire>(new Action<Stagiaire>(this.attach_Stagiaires), new Action<Stagiaire>(this.detach_Stagiaires));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPersonne", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idPersonne
		{
			get
			{
				return this._idPersonne;
			}
			set
			{
				if ((this._idPersonne != value))
				{
					this.OnidPersonneChanging(value);
					this.SendPropertyChanging();
					this._idPersonne = value;
					this.SendPropertyChanged("idPersonne");
					this.OnidPersonneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nom", DbType="VarChar(50)")]
		public string nom
		{
			get
			{
				return this._nom;
			}
			set
			{
				if ((this._nom != value))
				{
					this.OnnomChanging(value);
					this.SendPropertyChanging();
					this._nom = value;
					this.SendPropertyChanged("nom");
					this.OnnomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nomAr", DbType="NVarChar(50)")]
		public string nomAr
		{
			get
			{
				return this._nomAr;
			}
			set
			{
				if ((this._nomAr != value))
				{
					this.OnnomArChanging(value);
					this.SendPropertyChanging();
					this._nomAr = value;
					this.SendPropertyChanged("nomAr");
					this.OnnomArChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prenom", DbType="VarChar(50)")]
		public string prenom
		{
			get
			{
				return this._prenom;
			}
			set
			{
				if ((this._prenom != value))
				{
					this.OnprenomChanging(value);
					this.SendPropertyChanging();
					this._prenom = value;
					this.SendPropertyChanged("prenom");
					this.OnprenomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prenomAr", DbType="NVarChar(50)")]
		public string prenomAr
		{
			get
			{
				return this._prenomAr;
			}
			set
			{
				if ((this._prenomAr != value))
				{
					this.OnprenomArChanging(value);
					this.SendPropertyChanging();
					this._prenomAr = value;
					this.SendPropertyChanged("prenomAr");
					this.OnprenomArChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateNai", DbType="Date")]
		public System.Nullable<System.DateTime> dateNai
		{
			get
			{
				return this._dateNai;
			}
			set
			{
				if ((this._dateNai != value))
				{
					this.OndateNaiChanging(value);
					this.SendPropertyChanging();
					this._dateNai = value;
					this.SendPropertyChanged("dateNai");
					this.OndateNaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lieuNai", DbType="VarChar(50)")]
		public string lieuNai
		{
			get
			{
				return this._lieuNai;
			}
			set
			{
				if ((this._lieuNai != value))
				{
					this.OnlieuNaiChanging(value);
					this.SendPropertyChanging();
					this._lieuNai = value;
					this.SendPropertyChanged("lieuNai");
					this.OnlieuNaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lieuNaiAr", DbType="NVarChar(50)")]
		public string lieuNaiAr
		{
			get
			{
				return this._lieuNaiAr;
			}
			set
			{
				if ((this._lieuNaiAr != value))
				{
					this.OnlieuNaiArChanging(value);
					this.SendPropertyChanging();
					this._lieuNaiAr = value;
					this.SendPropertyChanged("lieuNaiAr");
					this.OnlieuNaiArChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sexe", DbType="VarChar(10)")]
		public string sexe
		{
			get
			{
				return this._sexe;
			}
			set
			{
				if ((this._sexe != value))
				{
					this.OnsexeChanging(value);
					this.SendPropertyChanging();
					this._sexe = value;
					this.SendPropertyChanged("sexe");
					this.OnsexeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adresse", DbType="VarChar(100)")]
		public string adresse
		{
			get
			{
				return this._adresse;
			}
			set
			{
				if ((this._adresse != value))
				{
					this.OnadresseChanging(value);
					this.SendPropertyChanging();
					this._adresse = value;
					this.SendPropertyChanged("adresse");
					this.OnadresseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adresseAr", DbType="NVarChar(50)")]
		public string adresseAr
		{
			get
			{
				return this._adresseAr;
			}
			set
			{
				if ((this._adresseAr != value))
				{
					this.OnadresseArChanging(value);
					this.SendPropertyChanging();
					this._adresseAr = value;
					this.SendPropertyChanged("adresseAr");
					this.OnadresseArChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(100)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telephone", DbType="VarChar(15)")]
		public string telephone
		{
			get
			{
				return this._telephone;
			}
			set
			{
				if ((this._telephone != value))
				{
					this.OntelephoneChanging(value);
					this.SendPropertyChanging();
					this._telephone = value;
					this.SendPropertyChanged("telephone");
					this.OntelephoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PersonnelInfo_Enseignant", Storage="_Enseignants", ThisKey="idPersonne", OtherKey="personnelInfosId")]
		public EntitySet<Enseignant> Enseignants
		{
			get
			{
				return this._Enseignants;
			}
			set
			{
				this._Enseignants.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PersonnelInfo_Stagiaire", Storage="_Stagiaires", ThisKey="idPersonne", OtherKey="personnelInfoId")]
		public EntitySet<Stagiaire> Stagiaires
		{
			get
			{
				return this._Stagiaires;
			}
			set
			{
				this._Stagiaires.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Enseignants(Enseignant entity)
		{
			this.SendPropertyChanging();
			entity.PersonnelInfo = this;
		}
		
		private void detach_Enseignants(Enseignant entity)
		{
			this.SendPropertyChanging();
			entity.PersonnelInfo = null;
		}
		
		private void attach_Stagiaires(Stagiaire entity)
		{
			this.SendPropertyChanging();
			entity.PersonnelInfo = this;
		}
		
		private void detach_Stagiaires(Stagiaire entity)
		{
			this.SendPropertyChanging();
			entity.PersonnelInfo = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Stagiaire")]
	public partial class Stagiaire : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _numInsc;
		
		private string _img;
		
		private string _statusStg;
		
		private string _idSection;
		
		private System.Nullable<int> _personnelInfoId;
		
		private System.Nullable<int> _detailsInfoId;
		
		private System.Nullable<int> _employeurId;
		
		private EntitySet<Note> _Notes;
		
		private EntityRef<DetailsStagiaire> _DetailsStagiaire;
		
		private EntityRef<Employeur> _Employeur;
		
		private EntityRef<PersonnelInfo> _PersonnelInfo;
		
		private EntityRef<Section> _Section;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnumInscChanging(string value);
    partial void OnnumInscChanged();
    partial void OnimgChanging(string value);
    partial void OnimgChanged();
    partial void OnstatusStgChanging(string value);
    partial void OnstatusStgChanged();
    partial void OnidSectionChanging(string value);
    partial void OnidSectionChanged();
    partial void OnpersonnelInfoIdChanging(System.Nullable<int> value);
    partial void OnpersonnelInfoIdChanged();
    partial void OndetailsInfoIdChanging(System.Nullable<int> value);
    partial void OndetailsInfoIdChanged();
    partial void OnemployeurIdChanging(System.Nullable<int> value);
    partial void OnemployeurIdChanged();
    #endregion
		
		public Stagiaire()
		{
			this._Notes = new EntitySet<Note>(new Action<Note>(this.attach_Notes), new Action<Note>(this.detach_Notes));
			this._DetailsStagiaire = default(EntityRef<DetailsStagiaire>);
			this._Employeur = default(EntityRef<Employeur>);
			this._PersonnelInfo = default(EntityRef<PersonnelInfo>);
			this._Section = default(EntityRef<Section>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numInsc", DbType="VarChar(50)")]
		public string numInsc
		{
			get
			{
				return this._numInsc;
			}
			set
			{
				if ((this._numInsc != value))
				{
					this.OnnumInscChanging(value);
					this.SendPropertyChanging();
					this._numInsc = value;
					this.SendPropertyChanged("numInsc");
					this.OnnumInscChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_img", DbType="VarChar(50)")]
		public string img
		{
			get
			{
				return this._img;
			}
			set
			{
				if ((this._img != value))
				{
					this.OnimgChanging(value);
					this.SendPropertyChanging();
					this._img = value;
					this.SendPropertyChanged("img");
					this.OnimgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_statusStg", DbType="VarChar(20)")]
		public string statusStg
		{
			get
			{
				return this._statusStg;
			}
			set
			{
				if ((this._statusStg != value))
				{
					this.OnstatusStgChanging(value);
					this.SendPropertyChanging();
					this._statusStg = value;
					this.SendPropertyChanged("statusStg");
					this.OnstatusStgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idSection", DbType="VarChar(10)")]
		public string idSection
		{
			get
			{
				return this._idSection;
			}
			set
			{
				if ((this._idSection != value))
				{
					if (this._Section.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidSectionChanging(value);
					this.SendPropertyChanging();
					this._idSection = value;
					this.SendPropertyChanged("idSection");
					this.OnidSectionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_personnelInfoId", DbType="Int")]
		public System.Nullable<int> personnelInfoId
		{
			get
			{
				return this._personnelInfoId;
			}
			set
			{
				if ((this._personnelInfoId != value))
				{
					if (this._PersonnelInfo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnpersonnelInfoIdChanging(value);
					this.SendPropertyChanging();
					this._personnelInfoId = value;
					this.SendPropertyChanged("personnelInfoId");
					this.OnpersonnelInfoIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_detailsInfoId", DbType="Int")]
		public System.Nullable<int> detailsInfoId
		{
			get
			{
				return this._detailsInfoId;
			}
			set
			{
				if ((this._detailsInfoId != value))
				{
					if (this._DetailsStagiaire.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OndetailsInfoIdChanging(value);
					this.SendPropertyChanging();
					this._detailsInfoId = value;
					this.SendPropertyChanged("detailsInfoId");
					this.OndetailsInfoIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_employeurId", DbType="Int")]
		public System.Nullable<int> employeurId
		{
			get
			{
				return this._employeurId;
			}
			set
			{
				if ((this._employeurId != value))
				{
					if (this._Employeur.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnemployeurIdChanging(value);
					this.SendPropertyChanging();
					this._employeurId = value;
					this.SendPropertyChanged("employeurId");
					this.OnemployeurIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Stagiaire_Note", Storage="_Notes", ThisKey="id", OtherKey="stgID")]
		public EntitySet<Note> Notes
		{
			get
			{
				return this._Notes;
			}
			set
			{
				this._Notes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DetailsStagiaire_Stagiaire", Storage="_DetailsStagiaire", ThisKey="detailsInfoId", OtherKey="id", IsForeignKey=true)]
		public DetailsStagiaire DetailsStagiaire
		{
			get
			{
				return this._DetailsStagiaire.Entity;
			}
			set
			{
				DetailsStagiaire previousValue = this._DetailsStagiaire.Entity;
				if (((previousValue != value) 
							|| (this._DetailsStagiaire.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DetailsStagiaire.Entity = null;
						previousValue.Stagiaires.Remove(this);
					}
					this._DetailsStagiaire.Entity = value;
					if ((value != null))
					{
						value.Stagiaires.Add(this);
						this._detailsInfoId = value.id;
					}
					else
					{
						this._detailsInfoId = default(Nullable<int>);
					}
					this.SendPropertyChanged("DetailsStagiaire");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Employeur_Stagiaire", Storage="_Employeur", ThisKey="employeurId", OtherKey="idEpoloyeur", IsForeignKey=true)]
		public Employeur Employeur
		{
			get
			{
				return this._Employeur.Entity;
			}
			set
			{
				Employeur previousValue = this._Employeur.Entity;
				if (((previousValue != value) 
							|| (this._Employeur.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Employeur.Entity = null;
						previousValue.Stagiaires.Remove(this);
					}
					this._Employeur.Entity = value;
					if ((value != null))
					{
						value.Stagiaires.Add(this);
						this._employeurId = value.idEpoloyeur;
					}
					else
					{
						this._employeurId = default(Nullable<int>);
					}
					this.SendPropertyChanged("Employeur");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PersonnelInfo_Stagiaire", Storage="_PersonnelInfo", ThisKey="personnelInfoId", OtherKey="idPersonne", IsForeignKey=true)]
		public PersonnelInfo PersonnelInfo
		{
			get
			{
				return this._PersonnelInfo.Entity;
			}
			set
			{
				PersonnelInfo previousValue = this._PersonnelInfo.Entity;
				if (((previousValue != value) 
							|| (this._PersonnelInfo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PersonnelInfo.Entity = null;
						previousValue.Stagiaires.Remove(this);
					}
					this._PersonnelInfo.Entity = value;
					if ((value != null))
					{
						value.Stagiaires.Add(this);
						this._personnelInfoId = value.idPersonne;
					}
					else
					{
						this._personnelInfoId = default(Nullable<int>);
					}
					this.SendPropertyChanged("PersonnelInfo");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Section_Stagiaire", Storage="_Section", ThisKey="idSection", OtherKey="codeSection", IsForeignKey=true)]
		public Section Section
		{
			get
			{
				return this._Section.Entity;
			}
			set
			{
				Section previousValue = this._Section.Entity;
				if (((previousValue != value) 
							|| (this._Section.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Section.Entity = null;
						previousValue.Stagiaires.Remove(this);
					}
					this._Section.Entity = value;
					if ((value != null))
					{
						value.Stagiaires.Add(this);
						this._idSection = value.codeSection;
					}
					else
					{
						this._idSection = default(string);
					}
					this.SendPropertyChanged("Section");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Notes(Note entity)
		{
			this.SendPropertyChanging();
			entity.Stagiaire = this;
		}
		
		private void detach_Notes(Note entity)
		{
			this.SendPropertyChanging();
			entity.Stagiaire = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Seance")]
	public partial class Seance : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _idSeance;
		
		private string _typeSeance;
		
		private System.Nullable<int> _VH;
		
		private string _idSec;
		
		private System.Nullable<int> _idEns;
		
		private System.Nullable<int> _idMod;
		
		private EntitySet<Exam> _Exams;
		
		private EntityRef<Enseignant> _Enseignant;
		
		private EntityRef<Module> _Module;
		
		private EntityRef<Section> _Section;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidSeanceChanging(string value);
    partial void OnidSeanceChanged();
    partial void OntypeSeanceChanging(string value);
    partial void OntypeSeanceChanged();
    partial void OnVHChanging(System.Nullable<int> value);
    partial void OnVHChanged();
    partial void OnidSecChanging(string value);
    partial void OnidSecChanged();
    partial void OnidEnsChanging(System.Nullable<int> value);
    partial void OnidEnsChanged();
    partial void OnidModChanging(System.Nullable<int> value);
    partial void OnidModChanged();
    #endregion
		
		public Seance()
		{
			this._Exams = new EntitySet<Exam>(new Action<Exam>(this.attach_Exams), new Action<Exam>(this.detach_Exams));
			this._Enseignant = default(EntityRef<Enseignant>);
			this._Module = default(EntityRef<Module>);
			this._Section = default(EntityRef<Section>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idSeance", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idSeance
		{
			get
			{
				return this._idSeance;
			}
			set
			{
				if ((this._idSeance != value))
				{
					this.OnidSeanceChanging(value);
					this.SendPropertyChanging();
					this._idSeance = value;
					this.SendPropertyChanged("idSeance");
					this.OnidSeanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_typeSeance", DbType="VarChar(10)")]
		public string typeSeance
		{
			get
			{
				return this._typeSeance;
			}
			set
			{
				if ((this._typeSeance != value))
				{
					this.OntypeSeanceChanging(value);
					this.SendPropertyChanging();
					this._typeSeance = value;
					this.SendPropertyChanged("typeSeance");
					this.OntypeSeanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VH", DbType="Int")]
		public System.Nullable<int> VH
		{
			get
			{
				return this._VH;
			}
			set
			{
				if ((this._VH != value))
				{
					this.OnVHChanging(value);
					this.SendPropertyChanging();
					this._VH = value;
					this.SendPropertyChanged("VH");
					this.OnVHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idSec", DbType="VarChar(10)")]
		public string idSec
		{
			get
			{
				return this._idSec;
			}
			set
			{
				if ((this._idSec != value))
				{
					if (this._Section.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidSecChanging(value);
					this.SendPropertyChanging();
					this._idSec = value;
					this.SendPropertyChanged("idSec");
					this.OnidSecChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEns", DbType="Int")]
		public System.Nullable<int> idEns
		{
			get
			{
				return this._idEns;
			}
			set
			{
				if ((this._idEns != value))
				{
					if (this._Enseignant.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidEnsChanging(value);
					this.SendPropertyChanging();
					this._idEns = value;
					this.SendPropertyChanged("idEns");
					this.OnidEnsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idMod", DbType="Int")]
		public System.Nullable<int> idMod
		{
			get
			{
				return this._idMod;
			}
			set
			{
				if ((this._idMod != value))
				{
					if (this._Module.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidModChanging(value);
					this.SendPropertyChanging();
					this._idMod = value;
					this.SendPropertyChanged("idMod");
					this.OnidModChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Seance_Exam", Storage="_Exams", ThisKey="idSeance", OtherKey="seanceID")]
		public EntitySet<Exam> Exams
		{
			get
			{
				return this._Exams;
			}
			set
			{
				this._Exams.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Enseignant_Seance", Storage="_Enseignant", ThisKey="idEns", OtherKey="idEnseiginant", IsForeignKey=true)]
		public Enseignant Enseignant
		{
			get
			{
				return this._Enseignant.Entity;
			}
			set
			{
				Enseignant previousValue = this._Enseignant.Entity;
				if (((previousValue != value) 
							|| (this._Enseignant.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Enseignant.Entity = null;
						previousValue.Seances.Remove(this);
					}
					this._Enseignant.Entity = value;
					if ((value != null))
					{
						value.Seances.Add(this);
						this._idEns = value.idEnseiginant;
					}
					else
					{
						this._idEns = default(Nullable<int>);
					}
					this.SendPropertyChanged("Enseignant");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Module_Seance", Storage="_Module", ThisKey="idMod", OtherKey="idModule", IsForeignKey=true)]
		public Module Module
		{
			get
			{
				return this._Module.Entity;
			}
			set
			{
				Module previousValue = this._Module.Entity;
				if (((previousValue != value) 
							|| (this._Module.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Module.Entity = null;
						previousValue.Seances.Remove(this);
					}
					this._Module.Entity = value;
					if ((value != null))
					{
						value.Seances.Add(this);
						this._idMod = value.idModule;
					}
					else
					{
						this._idMod = default(Nullable<int>);
					}
					this.SendPropertyChanged("Module");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Section_Seance", Storage="_Section", ThisKey="idSec", OtherKey="codeSection", IsForeignKey=true)]
		public Section Section
		{
			get
			{
				return this._Section.Entity;
			}
			set
			{
				Section previousValue = this._Section.Entity;
				if (((previousValue != value) 
							|| (this._Section.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Section.Entity = null;
						previousValue.Seances.Remove(this);
					}
					this._Section.Entity = value;
					if ((value != null))
					{
						value.Seances.Add(this);
						this._idSec = value.codeSection;
					}
					else
					{
						this._idSec = default(string);
					}
					this.SendPropertyChanged("Section");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Exams(Exam entity)
		{
			this.SendPropertyChanging();
			entity.Seance = this;
		}
		
		private void detach_Exams(Exam entity)
		{
			this.SendPropertyChanging();
			entity.Seance = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Exam")]
	public partial class Exam : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idExamen;
		
		private string _seanceID;
		
		private System.Nullable<int> _noteEli;
		
		private System.Nullable<int> _coef;
		
		private EntitySet<Note> _Notes;
		
		private EntityRef<Seance> _Seance;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidExamenChanging(int value);
    partial void OnidExamenChanged();
    partial void OnseanceIDChanging(string value);
    partial void OnseanceIDChanged();
    partial void OnnoteEliChanging(System.Nullable<int> value);
    partial void OnnoteEliChanged();
    partial void OncoefChanging(System.Nullable<int> value);
    partial void OncoefChanged();
    #endregion
		
		public Exam()
		{
			this._Notes = new EntitySet<Note>(new Action<Note>(this.attach_Notes), new Action<Note>(this.detach_Notes));
			this._Seance = default(EntityRef<Seance>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idExamen", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idExamen
		{
			get
			{
				return this._idExamen;
			}
			set
			{
				if ((this._idExamen != value))
				{
					this.OnidExamenChanging(value);
					this.SendPropertyChanging();
					this._idExamen = value;
					this.SendPropertyChanged("idExamen");
					this.OnidExamenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_seanceID", DbType="VarChar(20)")]
		public string seanceID
		{
			get
			{
				return this._seanceID;
			}
			set
			{
				if ((this._seanceID != value))
				{
					if (this._Seance.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnseanceIDChanging(value);
					this.SendPropertyChanging();
					this._seanceID = value;
					this.SendPropertyChanged("seanceID");
					this.OnseanceIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noteEli", DbType="Int")]
		public System.Nullable<int> noteEli
		{
			get
			{
				return this._noteEli;
			}
			set
			{
				if ((this._noteEli != value))
				{
					this.OnnoteEliChanging(value);
					this.SendPropertyChanging();
					this._noteEli = value;
					this.SendPropertyChanged("noteEli");
					this.OnnoteEliChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_coef", DbType="Int")]
		public System.Nullable<int> coef
		{
			get
			{
				return this._coef;
			}
			set
			{
				if ((this._coef != value))
				{
					this.OncoefChanging(value);
					this.SendPropertyChanging();
					this._coef = value;
					this.SendPropertyChanged("coef");
					this.OncoefChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Exam_Note", Storage="_Notes", ThisKey="idExamen", OtherKey="exmID")]
		public EntitySet<Note> Notes
		{
			get
			{
				return this._Notes;
			}
			set
			{
				this._Notes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Seance_Exam", Storage="_Seance", ThisKey="seanceID", OtherKey="idSeance", IsForeignKey=true)]
		public Seance Seance
		{
			get
			{
				return this._Seance.Entity;
			}
			set
			{
				Seance previousValue = this._Seance.Entity;
				if (((previousValue != value) 
							|| (this._Seance.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Seance.Entity = null;
						previousValue.Exams.Remove(this);
					}
					this._Seance.Entity = value;
					if ((value != null))
					{
						value.Exams.Add(this);
						this._seanceID = value.idSeance;
					}
					else
					{
						this._seanceID = default(string);
					}
					this.SendPropertyChanged("Seance");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Notes(Note entity)
		{
			this.SendPropertyChanging();
			entity.Exam = this;
		}
		
		private void detach_Notes(Note entity)
		{
			this.SendPropertyChanging();
			entity.Exam = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Notes")]
	public partial class Note : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idNote;
		
		private System.Nullable<int> _exmID;
		
		private System.Nullable<int> _stgID;
		
		private string _typeNote;
		
		private System.Nullable<decimal> _note1;
		
		private EntityRef<Exam> _Exam;
		
		private EntityRef<Stagiaire> _Stagiaire;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidNoteChanging(int value);
    partial void OnidNoteChanged();
    partial void OnexmIDChanging(System.Nullable<int> value);
    partial void OnexmIDChanged();
    partial void OnstgIDChanging(System.Nullable<int> value);
    partial void OnstgIDChanged();
    partial void OntypeNoteChanging(string value);
    partial void OntypeNoteChanged();
    partial void Onnote1Changing(System.Nullable<decimal> value);
    partial void Onnote1Changed();
    #endregion
		
		public Note()
		{
			this._Exam = default(EntityRef<Exam>);
			this._Stagiaire = default(EntityRef<Stagiaire>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idNote", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idNote
		{
			get
			{
				return this._idNote;
			}
			set
			{
				if ((this._idNote != value))
				{
					this.OnidNoteChanging(value);
					this.SendPropertyChanging();
					this._idNote = value;
					this.SendPropertyChanged("idNote");
					this.OnidNoteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_exmID", DbType="Int")]
		public System.Nullable<int> exmID
		{
			get
			{
				return this._exmID;
			}
			set
			{
				if ((this._exmID != value))
				{
					if (this._Exam.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnexmIDChanging(value);
					this.SendPropertyChanging();
					this._exmID = value;
					this.SendPropertyChanged("exmID");
					this.OnexmIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stgID", DbType="Int")]
		public System.Nullable<int> stgID
		{
			get
			{
				return this._stgID;
			}
			set
			{
				if ((this._stgID != value))
				{
					if (this._Stagiaire.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnstgIDChanging(value);
					this.SendPropertyChanging();
					this._stgID = value;
					this.SendPropertyChanged("stgID");
					this.OnstgIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_typeNote", DbType="VarChar(2)")]
		public string typeNote
		{
			get
			{
				return this._typeNote;
			}
			set
			{
				if ((this._typeNote != value))
				{
					this.OntypeNoteChanging(value);
					this.SendPropertyChanging();
					this._typeNote = value;
					this.SendPropertyChanged("typeNote");
					this.OntypeNoteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="note", Storage="_note1", DbType="Decimal(4,2)")]
		public System.Nullable<decimal> note1
		{
			get
			{
				return this._note1;
			}
			set
			{
				if ((this._note1 != value))
				{
					this.Onnote1Changing(value);
					this.SendPropertyChanging();
					this._note1 = value;
					this.SendPropertyChanged("note1");
					this.Onnote1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Exam_Note", Storage="_Exam", ThisKey="exmID", OtherKey="idExamen", IsForeignKey=true)]
		public Exam Exam
		{
			get
			{
				return this._Exam.Entity;
			}
			set
			{
				Exam previousValue = this._Exam.Entity;
				if (((previousValue != value) 
							|| (this._Exam.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Exam.Entity = null;
						previousValue.Notes.Remove(this);
					}
					this._Exam.Entity = value;
					if ((value != null))
					{
						value.Notes.Add(this);
						this._exmID = value.idExamen;
					}
					else
					{
						this._exmID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Exam");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Stagiaire_Note", Storage="_Stagiaire", ThisKey="stgID", OtherKey="id", IsForeignKey=true)]
		public Stagiaire Stagiaire
		{
			get
			{
				return this._Stagiaire.Entity;
			}
			set
			{
				Stagiaire previousValue = this._Stagiaire.Entity;
				if (((previousValue != value) 
							|| (this._Stagiaire.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Stagiaire.Entity = null;
						previousValue.Notes.Remove(this);
					}
					this._Stagiaire.Entity = value;
					if ((value != null))
					{
						value.Notes.Add(this);
						this._stgID = value.id;
					}
					else
					{
						this._stgID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Stagiaire");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Semestre")]
	public partial class Semestre : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idSemestre;
		
		private string _saison;
		
		private EntitySet<Section> _Sections;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidSemestreChanging(int value);
    partial void OnidSemestreChanged();
    partial void OnsaisonChanging(string value);
    partial void OnsaisonChanged();
    #endregion
		
		public Semestre()
		{
			this._Sections = new EntitySet<Section>(new Action<Section>(this.attach_Sections), new Action<Section>(this.detach_Sections));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idSemestre", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idSemestre
		{
			get
			{
				return this._idSemestre;
			}
			set
			{
				if ((this._idSemestre != value))
				{
					this.OnidSemestreChanging(value);
					this.SendPropertyChanging();
					this._idSemestre = value;
					this.SendPropertyChanged("idSemestre");
					this.OnidSemestreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_saison", DbType="VarChar(20)")]
		public string saison
		{
			get
			{
				return this._saison;
			}
			set
			{
				if ((this._saison != value))
				{
					this.OnsaisonChanging(value);
					this.SendPropertyChanging();
					this._saison = value;
					this.SendPropertyChanged("saison");
					this.OnsaisonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Semestre_Section", Storage="_Sections", ThisKey="idSemestre", OtherKey="semestreId")]
		public EntitySet<Section> Sections
		{
			get
			{
				return this._Sections;
			}
			set
			{
				this._Sections.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Sections(Section entity)
		{
			this.SendPropertyChanging();
			entity.Semestre = this;
		}
		
		private void detach_Sections(Section entity)
		{
			this.SendPropertyChanging();
			entity.Semestre = null;
		}
	}
}
#pragma warning restore 1591
