<?xml version="1.0" encoding="utf-8"?><Database Name="SuiveStagiaire" Class="myLinqToSqlDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-6AQC65B\SQLSERVER;Initial Catalog=SuiveStagiaire;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="SuiveStagiaireConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="groupID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="trustID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="User_Enseignant" Member="Enseignants" ThisKey="id" OtherKey="userId" Type="Enseignant" />
    </Type>
  </Table>
  <Table Name="dbo.Enseignant" Member="Enseignants">
    <Type Name="Enseignant">
      <Column Name="idEnseiginant" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="dateDebut" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="specialite" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="userId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="personnelInfosId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Enseignant_Seance" Member="Seances" ThisKey="idEnseiginant" OtherKey="idEns" Type="Seance" />
      <Association Name="User_Enseignant" Member="User" ThisKey="userId" OtherKey="id" Type="User" IsForeignKey="true" />
      <Association Name="PersonnelInfo_Enseignant" Member="PersonnelInfo" ThisKey="personnelInfosId" OtherKey="idPersonne" Type="PersonnelInfo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DetailsStagiaire" Member="DetailsStagiaires">
    <Type Name="DetailsStagiaire">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="sang" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="sitMedical" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="prenomPere" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="nomMere" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="prenomMere" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="telTuteur" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="nat" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="derEtabFre" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="nivScolaire" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="sitFam" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="profPere" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="profMere" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="sitFamParents" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Association Name="DetailsStagiaire_Stagiaire" Member="Stagiaires" ThisKey="id" OtherKey="detailsInfoId" Type="Stagiaire" />
    </Type>
  </Table>
  <Table Name="dbo.Branchees" Member="Branchees">
    <Type Name="Branchee">
      <Column Name="idBrache" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="libileBrache" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LibileBracheAr" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Branchee_CatalogeSection" Member="CatalogeSections" ThisKey="idBrache" OtherKey="brancheId" Type="CatalogeSection" />
    </Type>
  </Table>
  <Table Name="dbo.CatalogeSection" Member="CatalogeSections">
    <Type Name="CatalogeSection">
      <Column Name="idCataloge" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="brancheId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="codeSpe" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="intituleSpe" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="intituleSpeAr" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="fileresExigees" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="niveauFormation" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="CatalogeSection_Section" Member="Sections" ThisKey="idCataloge" OtherKey="idCat" Type="Section" />
      <Association Name="Branchee_CatalogeSection" Member="Branchee" ThisKey="brancheId" OtherKey="idBrache" Type="Branchee" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Module" Member="Modules">
    <Type Name="Module">
      <Column Name="idModule" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="libelle" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Module_Seance" Member="Seances" ThisKey="idModule" OtherKey="idMod" Type="Seance" />
    </Type>
  </Table>
  <Table Name="dbo.Employeur" Member="Employeurs">
    <Type Name="Employeur">
      <Column Name="idEpoloyeur" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Adresse" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="status" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="Employeur_Stagiaire" Member="Stagiaires" ThisKey="idEpoloyeur" OtherKey="employeurId" Type="Stagiaire" />
    </Type>
  </Table>
  <Table Name="dbo.Section" Member="Sections">
    <Type Name="Section">
      <Column Name="codeSection" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="dateOuv" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="dateFin" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="tuteurSection" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="modeGestionForm" Type="System.Char" DbType="NChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="semestreId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idCat" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Section_Stagiaire" Member="Stagiaires" ThisKey="codeSection" OtherKey="idSection" Type="Stagiaire" />
      <Association Name="Section_Seance" Member="Seances" ThisKey="codeSection" OtherKey="idSec" Type="Seance" />
      <Association Name="CatalogeSection_Section" Member="CatalogeSection" ThisKey="idCat" OtherKey="idCataloge" Type="CatalogeSection" IsForeignKey="true" />
      <Association Name="Semestre_Section" Member="Semestre" ThisKey="semestreId" OtherKey="idSemestre" Type="Semestre" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PersonnelInfo" Member="PersonnelInfos">
    <Type Name="PersonnelInfo">
      <Column Name="idPersonne" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nom" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="nomAr" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="prenom" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="prenomAr" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="dateNai" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="lieuNai" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="lieuNaiAr" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sexe" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="adresse" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="adresseAr" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="telephone" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Association Name="PersonnelInfo_Enseignant" Member="Enseignants" ThisKey="idPersonne" OtherKey="personnelInfosId" Type="Enseignant" />
      <Association Name="PersonnelInfo_Stagiaire" Member="Stagiaires" ThisKey="idPersonne" OtherKey="personnelInfoId" Type="Stagiaire" />
    </Type>
  </Table>
  <Table Name="dbo.Stagiaire" Member="Stagiaires">
    <Type Name="Stagiaire">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="numInsc" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="img" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="statusStg" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="idSection" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="personnelInfoId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="detailsInfoId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="employeurId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Stagiaire_Note" Member="Notes" ThisKey="id" OtherKey="stgID" Type="Note" />
      <Association Name="DetailsStagiaire_Stagiaire" Member="DetailsStagiaire" ThisKey="detailsInfoId" OtherKey="id" Type="DetailsStagiaire" IsForeignKey="true" />
      <Association Name="Employeur_Stagiaire" Member="Employeur" ThisKey="employeurId" OtherKey="idEpoloyeur" Type="Employeur" IsForeignKey="true" />
      <Association Name="PersonnelInfo_Stagiaire" Member="PersonnelInfo" ThisKey="personnelInfoId" OtherKey="idPersonne" Type="PersonnelInfo" IsForeignKey="true" />
      <Association Name="Section_Stagiaire" Member="Section" ThisKey="idSection" OtherKey="codeSection" Type="Section" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Seance" Member="Seances">
    <Type Name="Seance">
      <Column Name="idSeance" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="typeSeance" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="VH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idSec" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="idEns" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idMod" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Seance_Exam" Member="Exams" ThisKey="idSeance" OtherKey="seanceID" Type="Exam" />
      <Association Name="Enseignant_Seance" Member="Enseignant" ThisKey="idEns" OtherKey="idEnseiginant" Type="Enseignant" IsForeignKey="true" />
      <Association Name="Module_Seance" Member="Module" ThisKey="idMod" OtherKey="idModule" Type="Module" IsForeignKey="true" />
      <Association Name="Section_Seance" Member="Section" ThisKey="idSec" OtherKey="codeSection" Type="Section" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Exam" Member="Exams">
    <Type Name="Exam">
      <Column Name="idExamen" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="seanceID" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="noteEli" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="coef" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Exam_Note" Member="Notes" ThisKey="idExamen" OtherKey="exmID" Type="Note" />
      <Association Name="Seance_Exam" Member="Seance" ThisKey="seanceID" OtherKey="idSeance" Type="Seance" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Notes" Member="Notes">
    <Type Name="Note">
      <Column Name="idNote" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="exmID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="stgID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="typeNote" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="note" Member="note1" Type="System.Decimal" DbType="Decimal(4,2)" CanBeNull="true" />
      <Association Name="Exam_Note" Member="Exam" ThisKey="exmID" OtherKey="idExamen" Type="Exam" IsForeignKey="true" />
      <Association Name="Stagiaire_Note" Member="Stagiaire" ThisKey="stgID" OtherKey="id" Type="Stagiaire" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Semestre" Member="Semestres">
    <Type Name="Semestre">
      <Column Name="idSemestre" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="saison" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Association Name="Semestre_Section" Member="Sections" ThisKey="idSemestre" OtherKey="semestreId" Type="Section" />
    </Type>
  </Table>
</Database>